PROJECT = de1_sta

# Prototype Board FPGA family and device settings
# DE1
FAMILY = "Cyclone II"
DEVICE = EP2C20F484C7
PROGFILEEXT = sof

SOURCE_FILES = \
../../src/de1_sta.vhd

include ../makefile


