SYN_SOURCE_FILES = \
../../src/adcintf.vhd \
../../src/bclk.vhd \
../../src/dacintf.vhd \
../../src/fsgen.vhd \
../../src/i2c_sub.vhd \
../../src/i2c.vhd \
../../src/i2c_write.vhd \
../../src/mclk.vhd \
../../src/audio.vhd \
../../src/tone_rtl.vhd \
../../src/e_falling_edge_detector.vhd \
../../src/a_falling_edge_detector_fsm.vhd \
../../src/play_rtl.vhd \
../../src/count1s_rtl.vhd \
../../src/de1_play_structure.vhd \
../../src/phase_gen_rtl.vhd \
../../src/triangle_wave_gen_rtl.vhd

